# Generated by Django 5.2.1 on 2025-05-13 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='numero_recamaras',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='tipo_compra',
            field=models.CharField(choices=[('compra', 'Compra'), ('renta', 'Renta')], default='compra', max_length=10),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='tipo_inmueble',
            field=models.CharField(choices=[('casa', 'Casa'), ('departamento', 'Departamento'), ('terreno', 'Terreno')], default='casa', max_length=15),
        ),
    ]
