# Generated by Django 5.2.1 on 2025-05-14 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_alter_propiedad_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('me_interesa', models.CharField(choices=[('compra', 'Compra de propiedad'), ('renta', 'Renta de propiedad'), ('asesoria', 'Asesoría financiera')], max_length=20)),
                ('como_contactar', models.CharField(choices=[('telefono', 'Teléfono'), ('correo', 'Correo electrónico'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('comentarios', models.TextField(blank=True)),
            ],
        ),
    ]
