# Generated by Django 5.2.1 on 2025-05-19 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('documento', models.FileField(upload_to='documentos/')),
                ('ubicacion', models.CharField(choices=[('cdmx', 'Ciudad de México'), ('guadalajara', 'Guadalajara'), ('monterrey', 'Monterrey'), ('queretaro', 'Querétaro'), ('puebla', 'Puebla'), ('otro', 'Otra')], max_length=20)),
                ('tipo', models.CharField(choices=[('contrato', 'Contrato'), ('escritura', 'Escritura')], max_length=20)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
